import {tokenize,phrase} from "./tokens.js";
let shown=undefined,cues=[],active=null,media=null,tokens=[],anchor=null,source={kind:"video",title:"No media selected",locator:""};
const $=(id)=>document.getElementById(id);
const toMs=(raw)=>{const bits=raw.trim().replace(",",".").split(":").map(Number);const [h,m,s]=bits.length===3?bits:[0,bits[0],bits[1]];return Math.round((h*3600+m*60+s)*1000)};
const parse=(input)=>input.replace(/\r/g,"").trim().split(/\n{2,}/).flatMap((block)=>{const lines=block.split("\n").filter(Boolean);if(lines[0]?.startsWith("WEBVTT"))return[];const at=lines.findIndex((line)=>line.includes("-->"));if(at<0)return[];const [start,end]=lines[at].split("-->").map((part)=>part.trim().split(" ")[0]);const text=lines.slice(at+1).join(" ").replace(/<[^>]+>/g,"").trim();return text?[{index:0,startMs:toMs(start),endMs:toMs(end),text}]:[]}).map((cue,index)=>({...cue,index}));
const online=location.protocol.startsWith("http");
const status=(text)=>{$("status").textContent=text};
const api=async(path,init)=>{const res=await fetch(path,init);const body=res.headers.get("content-type")?.includes("json")?await res.json():await res.text();if(!res.ok)throw new Error(body.error??res.statusText);return body};
const fmt=(ms)=>`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,"0")}`;
function render(list){const rows=$("rows");if(!list.length){rows.innerHTML='<p class="muted">Captured encounters collect here. Deleting a flashcard never deletes this history.</p>';return}rows.replaceChildren(...list.map((e)=>{const row=document.createElement("div");row.className="row";const where=e.sourceKind==="web"?e.sourceTitle:`${e.sourceTitle} · ${fmt(e.startMs)}`;row.dataset.id=e.id;const thumb=document.createElement("div");thumb.className="thumb";if(e.screenshotPath){const img=document.createElement("img");img.src=`/api/card-media/${encodeURIComponent(e.screenshotPath.split("/").pop())}`;img.alt="";thumb.append(img)}if(e.audioClipPath){const b=document.createElement("button");b.className="play";b.type="button";b.textContent="▶";b.title="Play clip";const a=new Audio(`/api/card-media/${encodeURIComponent(e.audioClipPath.split("/").pop())}`);b.onclick=()=>a.play();thumb.append(b)}row.append(thumb);for(const [tag,value] of [["span",e.term],["span",e.definition||"No definition"],["p",e.sentence],["span",where]]){const node=document.createElement(tag);node.textContent=value;row.append(node)}const badge=document.createElement("span");badge.className=`badge ${e.cardStatus}`;badge.textContent={"new":"Not in Anki","exported":"In export file","in-anki":"In Anki","deleted":"Deleted in Anki"}[e.cardStatus]??"";if(e.cardStatus==="deleted"){const b=document.createElement("button");b.type="button";b.className="link";b.textContent="Re-send";b.onclick=async()=>{try{await api(`/api/encounters/${encodeURIComponent(e.id)}/resend`,{method:"POST"});status(`Re-sent “${e.term}” to Anki`);refresh()}catch(err){status(err.message)}};badge.append(" · ",b)}row.querySelector("span:last-of-type").append(document.createElement("br"),badge);return row}));$("count").textContent=`${list.length} saved`}
function renderLine(){anchor=null;tokens=active?tokenize(active.text):[];for(const id of ["caption","active"]){const el=$(id);if(!active){el.textContent=id==="active"?"No active subtitle":"";continue}el.replaceChildren(...tokens.map((t,i)=>{if(!t.word)return document.createTextNode(t.text);const b=document.createElement("button");b.type="button";b.className="tok";b.textContent=t.text;b.dataset.i=i;b.title="Click to save this word. Shift-click to extend to a phrase.";return b}))}}
function pick(event){const b=event.target.closest?.(".tok");if(!b||!active)return;const i=Number(b.dataset.i);if(event.shiftKey&&anchor!==null){$("term").value=phrase(tokens,anchor,i)}else{anchor=i;$("term").value=tokens[i].text}media?.pause();for(const el of document.querySelectorAll(".tok")){const k=Number(el.dataset.i);const lo=Math.min(anchor,i),hi=Math.max(anchor,i);el.classList.toggle("on",event.shiftKey?k>=lo&&k<=hi:k===i)}$("definition").focus();status(`Selected “${$("term").value}”.`);lookup($("term").value)}
let autoDef="",lookupSeq=0;
async function lookup(term){const seq=++lookupSeq;const box=$("lookup");if(!online||!term){box.hidden=true;return}let r=null;try{r=await api(`/api/lookup?term=${encodeURIComponent(term)}`)}catch{}if(seq!==lookupSeq)return;box.replaceChildren();if(!r){box.hidden=false;const p=document.createElement("p");p.className="fine";if(!dictCount){p.append("No dictionary yet. ");const b=document.createElement("button");b.type="button";b.className="link";b.textContent="Add a free one";b.onclick=openDicts;p.append(b,", and definitions fill in automatically.")}else p.textContent=`“${term}” isn't in your dictionaries. Type your own definition.`;box.append(p);return}
const def=$("definition");if(!def.value.trim()||def.value===autoDef){def.value=r.suggestion;autoDef=r.suggestion}
const head=document.createElement("div");head.className="lemma";head.textContent=r.lemma;if(r.via){const v=document.createElement("small");v.textContent=` ${r.via}`;head.append(v)}box.append(head);
const ol=document.createElement("ol");for(const g of [...new Set(r.senses.flatMap((x)=>x.glosses))].slice(0,6)){const li=document.createElement("li");const b=document.createElement("button");b.type="button";b.className="sense";b.textContent=g;b.title="Use this definition";b.onclick=()=>{const v=r.lemma!==r.query.trim()?`(${r.lemma}) ${g}`:g;def.value=v;autoDef=v};li.append(b);ol.append(li)}box.append(ol);box.hidden=false}
$("caption").addEventListener("click",pick);$("active").addEventListener("click",pick);
async function refresh(){if(!online){status("Open via `npm start` to save to your local database.");return}render(await api("/api/encounters"))}
let info={};
function attachPlayer(kind,src,title){$("source").textContent=title;media=document.createElement(kind);media.controls=true;media.src=src;media.ontimeupdate=()=>{const ms=media.currentTime*1000;active=cues.find((cue)=>cue.startMs<=ms&&ms<=cue.endMs);if(active!==shown){shown=active;renderLine()}$("hint").textContent=active?`${fmt(active.startMs)} · ready to save`:"Play into a subtitle cue first"};const slot=$("media-slot");slot.className="media";slot.replaceChildren(media);return media}
function loadOpened(m){source={kind:m.kind,title:m.name,locator:m.path};attachPlayer(m.kind,m.url,m.name);if(m.subtitles){cues=parse(m.subtitles.text);status(`${cues.length} subtitle lines loaded from ${m.subtitles.name}`)}else status(info.ffmpeg?"Loaded. Now load its SRT/VTT subtitles.":"Loaded. Install ffmpeg (brew install ffmpeg) to save a frame and audio clip with each card.");return m}
async function openPath(path){return loadOpened(await api("/api/open-media",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({path})}))}
window.contextDeck={openPath};
$("media").onclick=async(event)=>{if(!info.canPick)return;event.preventDefault();try{const m=await api("/api/pick-media",{method:"POST"});if(!m.cancelled)loadOpened(m)}catch(e){status(`Could not open: ${e.message}`)}};
$("media").onchange=(event)=>{const file=event.target.files?.[0];if(!file)return;source={kind:file.type.startsWith("audio")?"audio":"video",title:file.name,locator:`local:${file.name}:${file.size}`};attachPlayer(source.kind,URL.createObjectURL(file),file.name);status("Opened from the browser picker: frames and audio clips need the file path, so use npm start on macOS.")};
$("subs").onchange=async(event)=>{const file=event.target.files?.[0];if(file){cues=parse(await file.text());status(`${cues.length} subtitle lines loaded`)}};
$("save").onclick=async()=>{const term=$("term").value.trim();if(!active||!term){status("Play into a subtitle line and type a word first.");return}if(!online){status("Not saved: start the app with `npm start`.");return}try{const saved=await api("/api/encounters",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({source,cue:active,term,definition:$("definition").value.trim(),frameMs:media?Math.round(media.currentTime*1000):undefined})});$("term").value="";$("definition").value="";autoDef="";$("lookup").hidden=true;status(`Saved “${term}”${saved.screenshotPath||saved.audioClipPath?" with "+[saved.screenshotPath&&"frame",saved.audioClipPath&&"audio clip"].filter(Boolean).join(" and "):""}`);anchor=null;for(const el of document.querySelectorAll(".tok.on"))el.classList.remove("on");await refresh()}catch(e){status(`Save failed: ${e.message}`)}};
$("export").onclick=()=>{if(!online)return status("Start the app with `npm start` to export.");location.href="/api/export.tsv";status("Anki file downloading. In Anki: File > Import, pick context-deck-anki.txt.")};
$("import").onclick=async()=>{if(!online)return status("Start the app with `npm start` to import.");try{const r=await api("/api/import-captures",{method:"POST"});status(`Imported ${r.imported} new, ${r.skipped} already in deck${r.errors.length?`, ${r.errors.length} unreadable`:""} from ${r.captureDir}`);await refresh()}catch(e){status(`Import failed: ${e.message}`)}};
$("anki").onclick=async()=>{if(!online)return;status("Sending new cards to Anki…");try{const r=await api("/api/send-to-anki",{method:"POST"});const del=r.sync?.deletedInAnki?` Noticed ${r.sync.deletedInAnki} card${r.sync.deletedInAnki===1?"":"s"} deleted in Anki (history kept).`:"";status((r.sent||r.failed.length?`Sent ${r.sent} card${r.sent===1?"":"s"} to the “Context Deck” deck${r.failed.length?`, ${r.failed.length} skipped (${r.failed[0].error})`:""}.`:"Nothing new to send.")+del);refresh()}catch(e){status(e.message)}};
let dictCount=0,dictPoll=null;
const mb=(n)=>`${(n/1e6).toFixed(n>1e8?0:1)} MB`;
async function loadDicts(){const d=await api("/api/dictionaries");dictCount=d.installed.length;const list=$("dict-list");list.replaceChildren();if(!d.installed.length){const p=document.createElement("p");p.className="muted";p.textContent="No dictionaries yet.";list.append(p)}for(const x of d.installed){const row=document.createElement("div");row.className="dict";const name=document.createElement("span");name.textContent=x.title;const meta=document.createElement("small");meta.textContent=`${x.sourceLang??"?"} → ${x.targetLang??"?"} · ${x.entryCount.toLocaleString()} entries${x.revision?` · ${x.revision}`:""}`;const rm=document.createElement("button");rm.type="button";rm.className="link";rm.textContent="Remove";rm.onclick=async()=>{await api(`/api/dictionaries/${x.id}`,{method:"DELETE"});loadDicts()};row.append(name,meta,rm);list.append(row)}const sel=$("dict-lang");if(!sel.options.length)for(const c of d.catalog){const o=document.createElement("option");o.value=c.code;o.textContent=c.name;sel.append(o)}showJob(d.job);return d}
function showJob(j){const box=$("dict-progress");const busy=j.state==="downloading"||j.state==="importing";$("dict-download").disabled=busy;$("dict-file").disabled=busy;if(j.state==="idle"){box.hidden=true;return}box.hidden=false;const pct=j.total?Math.min(100,Math.round(j.bytes/j.total*100)):0;box.querySelector(".bar span").style.width=`${j.state==="done"?100:pct}%`;$("dict-progress-text").textContent=j.state==="downloading"?`Downloading ${j.label}… ${mb(j.bytes)}${j.total?` of ${mb(j.total)}`:""}`:j.state==="importing"?`Adding ${j.label}… ${j.entries.toLocaleString()} entries`:j.state==="done"?`Added ${j.title} (${j.entries.toLocaleString()} entries). Click any subtitle word to try it.`:`Couldn't add ${j.label}: ${j.error}`;if(busy&&!dictPoll)dictPoll=setInterval(async()=>{const d=await api("/api/dictionaries");showJob(d.job);if(d.job.state!=="downloading"&&d.job.state!=="importing"){clearInterval(dictPoll);dictPoll=null;loadDicts()}},700)}
async function openDicts(){if(!online)return status("Start the app with `npm start` to add dictionaries.");await loadDicts();$("dict-dialog").showModal()}
$("dicts").onclick=openDicts;
$("dict-download").onclick=async()=>{try{showJob(await api("/api/dictionaries/download",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:$("dict-lang").value})}))}catch(e){$("dict-progress").hidden=false;$("dict-progress-text").textContent=e.message}};
$("dict-file").onclick=async()=>{if(!info.canPick){$("dict-upload").click();return}try{const j=await api("/api/dictionaries/import-file",{method:"POST"});if(!j.cancelled)showJob(j)}catch(e){$("dict-progress-text").textContent=e.message}};
$("dict-upload").onchange=async(ev)=>{const f=ev.target.files?.[0];if(!f)return;try{showJob(await api(`/api/dictionaries/upload?name=${encodeURIComponent(f.name)}`,{method:"POST",body:f}))}catch(e){$("dict-progress-text").textContent=e.message}};
async function openDeepLink(){const q=new URLSearchParams(location.search);const id=q.get("source");if(!id)return;const src=await api(`/api/sources/${encodeURIComponent(id)}`);const t=Number(q.get("t")||0);const enc=q.get("encounter");if(enc)document.querySelector(`.row[data-id="${CSS.escape(enc)}"]`)?.classList.add("focus");if(src.kind==="web"){status(`From ${src.title}: ${src.locator}`);return}if(!src.available){status(`Original file not found: ${src.locator}`);return}loadOpened(src.media);media.addEventListener("loadedmetadata",()=>{media.currentTime=t/1000;media.play().catch(()=>{})},{once:true});status(`Opened ${src.title} at ${fmt(t)}`)}
window.contextDeck.openDeepLink=(link)=>{const u=new URL(link);const id=decodeURIComponent(u.pathname.replace(/^\/+/,"").split("/").pop());history.replaceState(null,"",`/?source=${encodeURIComponent(id)}&${u.searchParams}`);return refresh().then(openDeepLink)};
(async()=>{if(online){try{info=await api("/api/info")}catch{}try{dictCount=(await api("/api/dictionaries")).installed.length}catch{}}await refresh();await openDeepLink()})().catch((e)=>status(`Could not load deck: ${e.message}`));
