import {tokenize,phrase} from "./tokens.js";
let shown=undefined,cues=[],active=null,media=null,tokens=[],anchor=null,source={kind:"video",title:"No media selected",locator:""};
const $=(id)=>document.getElementById(id);
const toMs=(raw)=>{const bits=raw.trim().replace(",",".").split(":").map(Number);const [h,m,s]=bits.length===3?bits:[0,bits[0],bits[1]];return Math.round((h*3600+m*60+s)*1000)};
const parse=(input)=>input.replace(/\r/g,"").trim().split(/\n{2,}/).flatMap((block)=>{const lines=block.split("\n").filter(Boolean);if(lines[0]?.startsWith("WEBVTT"))return[];const at=lines.findIndex((line)=>line.includes("-->"));if(at<0)return[];const [start,end]=lines[at].split("-->").map((part)=>part.trim().split(" ")[0]);const text=lines.slice(at+1).join(" ").replace(/<[^>]+>/g,"").trim();return text?[{index:0,startMs:toMs(start),endMs:toMs(end),text}]:[]}).map((cue,index)=>({...cue,index}));
const online=location.protocol.startsWith("http");
const status=(text)=>{$("status").textContent=text};
const api=async(path,init)=>{const res=await fetch(path,init);const body=res.headers.get("content-type")?.includes("json")?await res.json():await res.text();if(!res.ok)throw new Error(body.error??res.statusText);return body};
const fmt=(ms)=>`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,"0")}`;
function render(list){const rows=$("rows");if(!list.length){rows.innerHTML='<p class="muted">Captured encounters collect here. Deleting a flashcard never deletes this history.</p>';return}rows.replaceChildren(...list.map((e)=>{const row=document.createElement("div");row.className="row";const where=e.sourceKind==="web"?e.sourceTitle:`${e.sourceTitle} · ${fmt(e.startMs)}`;for(const [tag,value] of [["span",e.term],["span",e.definition||"No definition"],["p",e.sentence],["span",where]]){const node=document.createElement(tag);node.textContent=value;row.append(node)}return row}));$("count").textContent=`${list.length} saved`}
function renderLine(){anchor=null;tokens=active?tokenize(active.text):[];for(const id of ["caption","active"]){const el=$(id);if(!active){el.textContent=id==="active"?"No active subtitle":"";continue}el.replaceChildren(...tokens.map((t,i)=>{if(!t.word)return document.createTextNode(t.text);const b=document.createElement("button");b.type="button";b.className="tok";b.textContent=t.text;b.dataset.i=i;b.title="Click to save this word. Shift-click to extend to a phrase.";return b}))}}
function pick(event){const b=event.target.closest?.(".tok");if(!b||!active)return;const i=Number(b.dataset.i);if(event.shiftKey&&anchor!==null){$("term").value=phrase(tokens,anchor,i)}else{anchor=i;$("term").value=tokens[i].text}media?.pause();for(const el of document.querySelectorAll(".tok")){const k=Number(el.dataset.i);const lo=Math.min(anchor,i),hi=Math.max(anchor,i);el.classList.toggle("on",event.shiftKey?k>=lo&&k<=hi:k===i)}$("definition").focus();status(`Selected “${$("term").value}”. Add a definition, then Save.`)}
$("caption").addEventListener("click",pick);$("active").addEventListener("click",pick);
async function refresh(){if(!online){status("Open via `npm start` to save to your local database.");return}render(await api("/api/encounters"))}
$("media").onchange=(event)=>{const file=event.target.files?.[0];if(!file)return;source={kind:file.type.startsWith("audio")?"audio":"video",title:file.name,locator:`local:${file.name}:${file.size}`};$("source").textContent=file.name;media=document.createElement(source.kind);media.controls=true;media.src=URL.createObjectURL(file);media.ontimeupdate=()=>{const ms=media.currentTime*1000;active=cues.find((cue)=>cue.startMs<=ms&&ms<=cue.endMs);if(active!==shown){shown=active;renderLine()}$("hint").textContent=active?`${fmt(active.startMs)} · ready to save`:"Play into a subtitle cue first"};const slot=$("media-slot");slot.className="media";slot.replaceChildren(media)};
$("subs").onchange=async(event)=>{const file=event.target.files?.[0];if(file){cues=parse(await file.text());status(`${cues.length} subtitle lines loaded`)}};
$("save").onclick=async()=>{const term=$("term").value.trim();if(!active||!term){status("Play into a subtitle line and type a word first.");return}if(!online){status("Not saved: start the app with `npm start`.");return}try{await api("/api/encounters",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({source,cue:active,term,definition:$("definition").value.trim()})});$("term").value="";$("definition").value="";status(`Saved “${term}”`);anchor=null;for(const el of document.querySelectorAll(".tok.on"))el.classList.remove("on");await refresh()}catch(e){status(`Save failed: ${e.message}`)}};
$("export").onclick=()=>{if(!online)return status("Start the app with `npm start` to export.");location.href="/api/export.tsv";status("Anki file downloading. In Anki: File > Import, pick context-deck-anki.txt.")};
$("import").onclick=async()=>{if(!online)return status("Start the app with `npm start` to import.");try{const r=await api("/api/import-captures",{method:"POST"});status(`Imported ${r.imported} new, ${r.skipped} already in deck${r.errors.length?`, ${r.errors.length} unreadable`:""} from ${r.captureDir}`);await refresh()}catch(e){status(`Import failed: ${e.message}`)}};
refresh().catch((e)=>status(`Could not load deck: ${e.message}`));
